SOURCE: SynthiaSeq
DATA_DIRECTORY_SOURCE: ../../video_seg/TPS/data/SynthiaSeq/SEQS-04-DAWN
DATA_LIST_SOURCE: tps/dataset/SynthiaSeq_list/train.txt
NUM_CLASSES: 12
generate_threshold_path: experiments_result/generate_synthina

TRAIN:
  LEARNING_RATE: 0.00025
  EARLY_STOP: 40000
  LAMBDA_T: 1.0
  
  SCALING_RATIO:
    - 0.8
    - 1.2
  flow_path_src: ../../video_seg/TPS/tps/data/estimated_optical_flow_synthiaseq_train
  DA_METHOD: TPS
  INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SET_SOURCE: train
  INPUT_SIZE_SOURCE:
    - 1280
    - 640
  SAVE_PRED_EVERY: 100
   
TEST:
   
  MODE: video_best # {'video_single', 'video_best', 'video_best_tcsm'}
  INFO_TARGET: tps/dataset/CityscapesSeq_list/info_SynthiaSeq.json
  SNAPSHOT_STEP: 100
  SNAPSHOT_START_ITER: 100
